### ISSUE TITLE
Build iOS app

### ISSUE THREAD

**Issue by fruzyna** [fruzyna/LiamRank#43]
So I've taken some time off partially because I was bored, partially because I ran out of easy features to add. This app seems to be entirely functional, including on iPads which is the most important platform. However, the goal was still to have a locally hosted application and after some research I had determined that there were no existing apps on the App Store which would suite this app's needs. It needs 2 apps in theory, a web server to host the files and a web browser to interact with them. Both of these exist for iOS. Unfortunately due to either the design of iOS or these existing apps none of the web servers appear to be able to reliably run while in the background, which is required because the web browser must be in the foreground. The only solution I see from here is a dedicated app which acts primarily as a web server (there are existing iOS libraries for this) and as a web browser, which can be accomplished with a webview of sorts. Additional features such as automatic updating of app resources would be useful. This should be reasonably feasible, but I don't have access to a Mac which makes development complicated to say the least.

**Comment by mail929** [comment]
Started Android app as first attempt: https://github.com/mail929/LiamRank-Android

**Comment by fruzyna** [comment]
Oh forgot this was open https://github.com/fruzyna/LiamRank-iOS
